name: The Highlighted Book
layout_spectrum: 0.2506112791597843
typography_spectrum: 0.6758215273730457
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.9551096979994327
  lightness: 0.7947454217355698
  saturation: 0.4027710296213627
  rhythmicContrast: 0.17971003171987832
title: >-
  This is The Highlighted Book. We have read some great books, but sometimes
  there is just those highlighted parts that make think,

  Wow
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: true
navigation:
  - name: Why do we say life is short!
    id: 56567dd3-bd70-4495-8093-8c57bb8f9041
    type: content
coverPrefs:
  filter: false
