name: The Highlighted Book
layout_spectrum: 0.38911801390349865
typography_spectrum: 0.9020008225925267
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.03719299053773284
  lightness: 0.705765588209033
  saturation: 0.9490417100023478
  rhythmicContrast: 0.3068306874483824
title: The Highlighted Book
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: true
navigation:
  - name: Why do we say life is short!
    id: 56567dd3-bd70-4495-8093-8c57bb8f9041
    type: content
