name: The Highlighted Book
layout_spectrum: 0.8845537018496543
typography_spectrum: 0.7437389807309955
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.6706874642986804
  lightness: 0.6518162414431572
  saturation: 0.31326544005423784
  rhythmicContrast: 0.31013030163012445
title: >-
  This is The Highlighted Book. We have read some great books, but sometimes
  there is just those highlighted parts that make think,

  Wow
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: true
navigation:
  - name: Why do we say life is short!
    id: 56567dd3-bd70-4495-8093-8c57bb8f9041
    type: content
coverPrefs:
  filter: false
